# Define the build steps
steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '--single-branch', '--depth=1', 'https://github.com/karan8891/dataproc-cloudbuild.git', 'cloudbuild']
- name: 'gcloud'
  args: ['dataproc', 'workflow-templates', 'import', 'workflow/workflow.yaml']
  secretEnv:
    - 'MY_SECRET'

# Define triggers (e.g., on push to main branch)
triggers:
- github:
    branch: main

# Substitute placeholders with your details
# - <your-username>: Your GitHub username
# - <your-repo>: Your GitHub repository name
# - <source-directory>: Directory in the workspace to clone the repo (e.g., 'src')
# - <your-template-file>.yaml: The name of your workflow template file
